INSERT INTO ENVIO (ID, ORIGEN, DESTINO, FECHA_ENVIO, COSTO) VALUES (1, 'Isla Negra', 'Santiago', TO_DATE('2025-04-25', 'YYYY-MM-DD'), 9900);
INSERT INTO ENVIO (ID, ORIGEN, DESTINO, FECHA_ENVIO, COSTO) VALUES (2, 'Valparaíso', 'Lima', TO_DATE('2025-04-26', 'YYYY-MM-DD'), 33000);
INSERT INTO ENVIO (ID, ORIGEN, DESTINO, FECHA_ENVIO, COSTO) VALUES (3, 'La Serena', 'Arequipa', TO_DATE('2025-04-27', 'YYYY-MM-DD'), 45000);

COMMIT;
